### ISSUE TITLE
get-a-quote/hover misisng

### ISSUE THREAD

**Issue by asif-mahmood-com** [asif-mahmood-com/palmer-lck-citadel#11]
hover missing
http://prntscr.com/m5v4ex + http://prntscr.com/m5v6mi + http://prntscr.com/m5vito + http://prntscr.com/m5vjo6

**Comment by Aamir-Aslam-com** [comment]
The buttons already have default hover effect according to hubspot and there are no hover over color instructions with in given PDF file. About the links hover overs also we don't have instructions about these if you need some effect on these please let me know the color code I will add.

**Comment by asif-mahmood-com** [comment]
Old Bugs
