### ISSUE TITLE
get-a-quote/ uppercase

### ISSUE THREAD

**Issue by asif-mahmood-com** [asif-mahmood-com/palmer-lck-citadel#2]
text should be in uppercase from css.
http://prntscr.com/m5ugmc + http://prntscr.com/m5ut5j + http://prntscr.com/m5utny + http://prntscr.com/m5v2uc + http://prntscr.com/m5vito

**Comment by Aamir-Aslam-com** [comment]
We have fixed the issue.

**Comment by asif-mahmood-com** [comment]
Old Bugs
