### ISSUE TITLE
get-a-quote/font size issue

### ISSUE THREAD

**Issue by asif-mahmood-com** [asif-mahmood-com/palmer-lck-citadel#9]
font size to big need to manage according to screen.
http://prntscr.com/m5v18z + http://prntscr.com/m5v1o0  + http://prntscr.com/m5v5kf + http://prntscr.com/m5v8i9

**Comment by Aamir-Aslam-com** [comment]
Font Size has been fixed accordingly.

**Comment by asif-mahmood-com** [comment]
Old Bugs
